<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <AssemblyName>StarLead</AssemblyName>
    <Product>星引</Product>
    <Version>0.32.0</Version>
    <ApplicationIcon>Assets\StarLead.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\StarLead.png" />
    <Resource Include="Assets\StarLead-mark-white.png" />
    <Resource Include="Assets\StarLead-mark-black.png" />
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

</Project>
